# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DPdYbIMCMyq8QXysOPsbA5bmcK1OnR1U
"""

# -*- coding: utf-8 -*-

import tensorflow as tf
import numpy as np

# Definir los datos de entrenamiento
galones = np.array([1, 2, 3, 4, 5], dtype=float)  # Cambié los valores para representar galones
centimetros_cubicos = np.array([3785.41, 7570.82, 11356.2, 15141.6, 18927], dtype=float)  # Conversión de galones a cm^3

# Definir la fórmula de conversión de galones a centímetros cúbicos
def galones_a_cm3(galones):
    return galones * 3785.41  # 1 galón ≈ 3785.41 cm^3

# Crear el modelo
oculta1 = tf.keras.layers.Dense(units=3, input_shape=[1])
oculta2 = tf.keras.layers.Dense(units=3)
salida = tf.keras.layers.Dense(units=1)
modelo = tf.keras.Sequential([oculta1, oculta2, salida])

# Compilar el modelo
modelo.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

# Entrenar el modelo
print("Comenzando entrenamiento...")
historial = modelo.fit(galones, centimetros_cubicos, epochs=1000, verbose=False)
print("Modelo entrenado!!!")

# Realizar una predicción
print("Realizar una predicción")
resultado = modelo.predict([10.0])  # Cambié el valor de predicción a 10 galones
print("El resultado es " + str(resultado) + " centímetros cúbicos")

# Guardar el modelo
modelo.save('galones_a_cmcubicos.h5')

# Convertir 10 galones a centímetros cúbicos
galones = 10
cm3 = galones_a_cm3(galones)
print("10 galones son " + str(cm3) + " centímetros cúbicos")

!ls

!pip install tensorflowjs

!mkdir recuperacion

!tensorflowjs_converter --input_format keras galones_a_cmcubicos.h5 recuperacion

!ls